### ISSUE TITLE
Murmur Linux Ermine zero-ermine-ld.py hashlib warnings

### ISSUE THREAD

**Issue by hacst** [mumble-voip/mumble-releng#19]
Python's hashlib seems to be pretty unhappy:

```
+ zero-ermine-ld.py tarball-root/murmur.x86
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/MumbleBuild/centos-ermine-1.3.x-2015-10-17-765bc7f-521~dirty/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/MumbleBuild/centos-ermine-1.3.x-2015-10-17-765bc7f-521~dirty/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/MumbleBuild/centos-ermine-1.3.x-2015-10-17-765bc7f-521~dirty/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/MumbleBuild/centos-ermine-1.3.x-2015-10-17-765bc7f-521~dirty/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/MumbleBuild/centos-ermine-1.3.x-2015-10-17-765bc7f-521~dirty/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/MumbleBuild/centos-ermine-1.3.x-2015-10-17-765bc7f-521~dirty/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/MumbleBuild/centos-ermine-1.3.x-2015-10-17-765bc7f-521~dirty/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/MumbleBuild/centos-ermine-1.3.x-2015-10-17-765bc7f-521~dirty/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/MumbleBuild/centos-ermine-1.3.x-2015-10-17-765bc7f-521~dirty/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/MumbleBuild/centos-ermine-1.3.x-2015-10-17-765bc7f-521~dirty/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/MumbleBuild/centos-ermine-1.3.x-2015-10-17-765bc7f-521~dirty/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/MumbleBuild/centos-ermine-1.3.x-2015-10-17-765bc7f-521~dirty/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
```

A quick google suggests it might be missing OpenSSL (e.g. http://stackoverflow.com/questions/20399331/error-importing-hashlib-with-python-2-7-but-not-with-2-6).

Don't think I have access to that box.

**Comment by mkrautz** [comment]
We built the Python version ourselves.

https://github.com/mumble-voip/mumble-releng/blob/master/buildenv/1.3.x/centos-ermine/python.build

**Comment by mkrautz** [comment]
Fixed via https://github.com/mumble-voip/mumble-releng/commit/293077d28d3ecdfcbbc88738924e9e3a2948dc07.
